@startuml
interface PropertyEditor
interface PropertyEditorRegistry
PropertyEditor -* PropertyEditorRegistrySupport
PropertyEditorRegistry <|--PropertyEditorRegistrySupport
PropertyEditorRegistrySupport <|-- BeanWrapperImpl
@enduml